### ISSUE TITLE
Intermittent connection failures

### ISSUE THREAD

**Issue by droopanu** [mezz64/pyEight#3]
I noticed that the eight component in homeassistant fails to connect most of the time.

After a bit of investigation, I changed the DEFAULT_TIMEOUT from 10 to 60 in constants.py and I haven't seen any issues since.

**Comment by mezz64** [comment]
Glad to hear that worked for you.  I don't really see a downside so i'll make the change along with some api updates to sync up with the new app releases.

**Comment by mezz64** [comment]
PR is pending for homeassistant to move to pyEight 0.0.8 with the timeout increased.
