### ISSUE TITLE
Set away mode

### ISSUE THREAD

**Issue by robbinonline** [mezz64/pyEight#39]
From the latest discovery I see set away mode is possible. It would be great if this could be implemented in the home assistant integration

**Comment by mezz64** [comment]
It is unfortunately only possible with the new OAuth API endpoints.  Eight has not published a way to obtain that key officially and I have no plans to implement what can be sniffed from the APP as I have no way of knowing if it's unique nor it's refresh cycle.

Closing this as there is nothing I can do to implement unless they open up their API.
