### ISSUE TITLE
Home Assistant Single Sleeper 

### ISSUE THREAD

**Issue by rcasad** [mezz64/pyEight#4]
Setting up Eight with home assistant first assumes a single sleeper is on the left, and to my knowledge is supposed switch to the right side of the left throws an error. Not working in my case, sensors showing for left even though no data is being provided and no data or sensors for right side, even though data is available.

**Comment by mezz64** [comment]
I think I was able to identify and fix the problem.  The changes didn't break anything in my test code so I went ahead and pushed an update to pypi.  You can test it out on your local install by editing the line:
`REQUIREMENTS = ['pyeight==0.0.9']`  to  `REQUIREMENTS = ['pyeight==0.1.0']`
in the `homeassistant/components/eight_sleep.py` file.

A restart of hass should pull the new version from pypi automatically after the change.

Let me know if it fixes things for you and i'll submit a PR to get the library updated in hass upstream.

**Comment by mezz64** [comment]
A fix was just merged into hass upstream dev.  Should be good moving forward.
